version: '3'
services:
  vue-app:
    build:
      context: .
    ports:
      - '8080:8080'
    depends_on:
      - api
  api:
    build:
      context: ../face-count-api
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: file:./db.sqlite
#    env_file:
#      - ../face-count-api/.env
#  redis:
#    image: redis:latest
#    ports:
#      - "6379:6379"
